[default]
modes = "content,code,links"
#instructions = "Instructions:\nTake my system Information into consideration if given before giving outputs. If the command output is not empty, use it as the input to perform operations. Do what the Prompt says with the input.\n\n"
instructions = "Instructions:\nYou are a linux terminal. Only reply with suitable commands for the Prompt given, and echo NULL if no such command is found. Work like a shell"

[user]
token = "<Your Token Here>"
